import { FileText, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { ApiStateNotice } from "../common/ApiStateNotice";
import type { CandidateMemo } from "../../api/candidates";

export function InvestmentMemo({ memo, memoError, memoLoading, memoGenState, onGenerate, onRetryMemo }: { memo: CandidateMemo | null | undefined; memoError: unknown; memoLoading: boolean; memoGenState: "idle" | "queued" | "error"; onGenerate: () => void; onRetryMemo: () => void }) {
  const hasMemo = memo?.status === "succeeded" && memo.sections.length > 0;
  const hasDraft = Boolean(memo && memo.status !== "missing" && memo.status !== "pending" && memo.sections.length > 0);
  const memoStatus = memo?.status === "degraded" ? "Degraded draft · not decision-ready" : memo?.status === "failed" ? "Generation failed · not decision-ready" : memo?.status === "pending" ? "Generation pending" : null;
  const renderableMemo = memo && (hasMemo || hasDraft) ? memo : null;

  return <section className="panel rounded-lg p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-gradient-to-r from-[#edf3fb] to-[#eef6f3] px-4 py-3.5"><div><div className="eyebrow mb-2 flex items-center gap-1.5"><FileText className="h-3.5 w-3.5" /> Investment memo</div><h2 className="text-lg font-bold">Detailed IC report</h2></div><div className="flex items-center gap-2">{(hasMemo || hasDraft) && <span className="status-pill bg-surface-2 text-muted">{hasMemo ? `${memo.generation_mode === "agent" ? "AI generated" : "Validated memo"} · ${memo.model_version ?? "unknown"}` : memoStatus}</span>}{!hasMemo && !memoLoading && memo?.status !== "pending" && <button onClick={onGenerate} disabled={memoGenState === "queued"} className="inline-flex items-center gap-1.5 rounded-md bg-accent px-3 py-2 text-[10px] font-bold text-white disabled:opacity-60">{memoGenState === "queued" ? <><Loader2 className="h-3 w-3 animate-spin" /> Generating…</> : memoGenState === "error" ? <><RefreshCw className="h-3 w-3" /> Retry</> : <><Sparkles className="h-3.5 w-3.5" /> Generate memo</>}</button>}</div></div>{memoLoading && <div className="mt-5 flex items-center justify-center gap-2 py-10 text-xs text-muted"><Loader2 className="h-4 w-4 animate-spin" /> Loading memo…</div>}{memoError != null && <div className="mt-5"><ApiStateNotice error={memoError} onRetry={onRetryMemo} label="investment memo" /></div>}{!memoLoading && memoStatus && <div role="alert" className="mt-5 rounded-md border border-warn/25 bg-[#fff8ed] p-4 text-xs text-[#8d5e2b]">{memoStatus}. It cannot advance the opportunity to memo-ready until a validated memo succeeds.</div>}{!memoLoading && renderableMemo && <div className="mt-5 grid gap-x-7 gap-y-6 xl:grid-cols-2">{renderableMemo.sections.map((section) => <div key={section.title}><MemoHeading icon={FileText} title={section.title} /><p className="mt-3 text-xs leading-6 text-ink-2">{section.text}</p>{section.evidence_ids.length > 0 && <p className="mt-2 text-[10px] text-muted-2">{section.evidence_ids.length} evidence reference{section.evidence_ids.length === 1 ? "" : "s"}</p>}</div>)}</div>}{!memoLoading && !memoError && !hasMemo && memo?.status !== "pending" && memoGenState === "idle" && <div className="mt-5 rounded-md bg-surface-2 p-4 text-center text-xs text-muted">No investment memo has been generated yet. Click "Generate memo" to create one from the available evidence.</div>}{!memoLoading && !hasMemo && memo?.status !== "pending" && memoGenState === "queued" && <div className="mt-5 rounded-md bg-surface-2 p-4 text-center text-xs text-muted">Memo generation has been queued. It will appear here once complete.</div>}{!memoLoading && !hasMemo && memo?.status !== "pending" && memoGenState === "error" && <div className="mt-5 rounded-md bg-[#fff1df] p-4 text-center text-xs text-[#a96e2d]">Memo generation failed. Please retry.</div>}</section>;
}

function MemoHeading({ icon: Icon, title }: { icon: React.ElementType; title: string }) {
  return <div className="flex items-center gap-2 text-xs font-bold"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-accent-soft text-accent"><Icon className="h-3.5 w-3.5" /></span>{title}</div>;
}
