import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, Scale, ShieldCheck } from "lucide-react";

const cases=[
 {company:"NeuraGrid",founder:"Alice Chen",stage:"Final diligence",deadline:"6h 20m",recommendation:"Proceed",match:91,risk:"Verify contracted ARR",tone:"green"},
 {company:"RelayOps",founder:"Marcus Johnson",stage:"Memo ready",deadline:"11h 05m",recommendation:"Hold",match:68,risk:"Technical defensibility",tone:"amber"},
 {company:"Kanso Robotics",founder:"Yuki Tanaka",stage:"Screening",deadline:"18h 40m",recommendation:"Investigate",match:79,risk:"Commercial co-founder",tone:"blue"},
];
export function DecisionQueuePage(){return <div className="mx-auto max-w-[1100px] pb-10"><div className="mb-7"><div className="eyebrow mb-2">Human approval</div><h1 className="text-3xl font-bold tracking-tight">Decision queue</h1><p className="mt-2 text-sm text-muted">Investment cases requiring review, ordered by SLA risk and readiness.</p></div><div className="mb-5 grid gap-3 sm:grid-cols-3"><QueueMetric icon={Scale} label="Ready for decision" value="3" tone="blue"/><QueueMetric icon={Clock3} label="Due within 12 hours" value="2" tone="amber"/><QueueMetric icon={CheckCircle2} label="Decided this week" value="14" tone="green"/></div><div className="space-y-3">{cases.map(item=><article key={item.company} className="panel rounded-lg p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-[220px] items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-accent-soft font-bold text-accent">{item.company.slice(0,2).toUpperCase()}</span><div><h2 className="text-sm font-bold">{item.company}</h2><p className="text-[11px] text-muted">{item.founder} · {item.stage}</p></div></div><div className="grid flex-1 grid-cols-2 gap-3 md:grid-cols-4"><Datum label="Thesis match" value={`${item.match}%`} icon={ShieldCheck}/><Datum label="Recommendation" value={item.recommendation} icon={Scale}/><Datum label="Top open risk" value={item.risk} icon={AlertTriangle}/><Datum label="SLA remaining" value={item.deadline} icon={Clock3}/></div><button className="flex items-center justify-center gap-1 rounded-md bg-accent px-4 py-2.5 text-xs font-bold text-white">Review <ArrowRight className="h-3.5 w-3.5"/></button></div></article>)}</div></div>}
function QueueMetric({icon:Icon,label,value,tone}:{icon:React.ElementType;label:string;value:string;tone:"blue"|"amber"|"green"}){const tones={blue:"bg-[#e7eef9] text-[#5074a8]",amber:"bg-[#fff1df] text-[#a96e2d]",green:"bg-[#e4f2ed] text-[#347c67]"};return <div className="panel flex items-center gap-3 rounded-lg p-4"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${tones[tone]}`}><Icon className="h-4 w-4"/></span><div><div className="text-lg font-bold">{value}</div><div className="text-[10px] text-muted">{label}</div></div></div>}
function Datum({label,value,icon:Icon}:{label:string;value:string;icon:React.ElementType}){return <div><div className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-muted-2"><Icon className="h-3 w-3"/>{label}</div><div className="mt-1 truncate text-[11px] font-semibold text-ink-2">{value}</div></div>}
