import { useNavigate, useParams } from "react-router";
import { Activity, ArrowLeft, ArrowUpRight, Award, Bookmark, Building2, CalendarDays, CheckCircle2, CircleAlert, Crosshair, FileText, Github, Globe2, Linkedin, Mail, MessageSquare, Network, ShieldCheck, Sparkles, TrendingUp, UserRound, Users } from "lucide-react";
import { mockCandidates } from "../data/mockCandidates";
import { getMockFounderProfile, type FounderRelation } from "../data/mockFounderProfiles";

export function FounderProfilePage(){
 const {founderId}=useParams(); const navigate=useNavigate(); const founder=mockCandidates.find(c=>c.id===founderId)??mockCandidates[0]; const profile=getMockFounderProfile(founder.stable_id);
 return <div className="pb-8">
   <button onClick={()=>navigate('/sourcing')} className="mb-5 flex items-center gap-2 text-xs font-semibold text-muted hover:text-accent"><ArrowLeft className="h-4 w-4"/>Back to discovery</button>
   <section className="panel mb-5 rounded-lg p-5 md:p-7">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-start">
      <div className="flex min-w-0 flex-1 gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-[#dbe6f2] to-[#bdcbdd] text-xl font-bold text-accent shadow-inner">{profile.initials}</div><div><div className="mb-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{founder.display_name}</h1><CheckCircle2 className="h-4 w-4 text-success"/><span className="rounded-full bg-[#e9f4ef] px-2.5 py-1 text-[10px] font-bold text-success">IDENTITY VERIFIED</span></div><div className="text-sm font-semibold text-ink-2">{profile.role} · {profile.company}</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted"><span>{profile.location}</span><span>{profile.stage}</span><span>{profile.sector}</span></div><div className="mt-3 flex gap-2"><Social icon={Linkedin}/><Social icon={Github}/><Social icon={Globe2}/><Social icon={Mail}/></div></div></div>
      <div className="flex gap-2"><button className="flex items-center gap-2 rounded-md border border-line px-3.5 py-2.5 text-xs font-semibold text-ink-2"><Bookmark className="h-4 w-4"/>Save</button><button className="flex items-center gap-2 rounded-md bg-accent px-4 py-2.5 text-xs font-semibold text-white"><MessageSquare className="h-4 w-4"/>Start outreach</button></div>
    </div>
    <p className="mt-6 max-w-4xl text-sm leading-6 text-muted">{profile.summary}</p>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Score icon={Award} tone="blue" label="Founder score" value={String(profile.founderScore)} hint={profile.scoreHint}/><Score icon={Activity} tone="purple" label="Execution momentum" value={String(profile.momentum)} hint="Trajectory signal"/><Score icon={Crosshair} tone="green" label="Thesis alignment" value={String(profile.thesisFit)} hint="Active thesis version"/><Score icon={ShieldCheck} tone="amber" label="Evidence confidence" value={String(profile.evidence)} hint={`${profile.gaps.length} open truth gaps`} warning/></div>
   </section>

   <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]">
    <div className="space-y-5">
      <Section title="Opportunity assessment" subtitle="Independent axes — not averaged" icon={Sparkles}>
        <div className="grid gap-3 md:grid-cols-3">{profile.assessments.map(item=><Assessment key={item.title} {...item}/>)}</div>
      </Section>
      <Section title="Founder journey" subtitle="Time-aware milestones with source confidence" icon={CalendarDays}>
        <div className="relative ml-2 border-l border-[#ced9e7] pl-6">{profile.events.map((e,i)=>{const tone=eventTone(e.type);return <div key={e.title} className={`${i===profile.events.length-1?"pb-0":"pb-7"} relative`}><span className={`absolute -left-[30px] top-1 h-3 w-3 rounded-full border-[3px] border-white shadow-[0_0_0_1px_#9eafc4] ${tone.dot}`}/><div className="mb-1 flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold text-accent">{e.date}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${tone.badge}`}>{e.type}</span><span className="ml-auto flex items-center gap-1 text-[10px] text-muted"><ShieldCheck className="h-3 w-3 text-success"/>Trust {e.trust}%</span></div><h4 className="text-sm font-bold">{e.title}</h4><p className="mt-1 text-xs leading-5 text-muted">{e.body}</p></div>})}</div>
      </Section>
      <Section title="Claims & evidence" subtitle="Every claim preserves provenance, freshness and trust" icon={ShieldCheck}>
        <div className="space-y-2.5">{profile.claims.map(c=><div key={c.claim} className="rounded-lg border border-line bg-surface-2 p-4"><div className="flex gap-3"><div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-md ${c.trust>80?"bg-[#e4f2ed] text-success":c.trust>65?"bg-[#fff2df] text-warn":"bg-[#fbe9e9] text-danger"}`}>{c.trust>80?<CheckCircle2 className="h-4 w-4"/>:<CircleAlert className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h4 className="text-xs font-bold leading-5">{c.claim}</h4><span className="shrink-0 text-xs font-bold text-accent">{c.trust}%</span></div><p className="mt-1 text-[11px] text-muted">{c.source}</p><div className="mt-2 text-[10px] font-semibold text-muted">{c.status}</div></div></div></div>)}</div>
      </Section>
    </div>
    <div className="space-y-5">
      <Section title="Relationship network" subtitle="People, companies and institutions" icon={Network}><RelationshipGraph founderName={founder.display_name ?? "Founder"} initials={profile.initials} relations={profile.relations}/></Section>
      <Section title="Evidence coverage" subtitle="Missing evidence lowers confidence, not merit" icon={FileText}>
       <div className="space-y-4">{profile.coverage.map(item=><Coverage key={item.label} {...item}/>)}</div>
       <div className="mt-5 rounded-lg bg-[#fff8ed] p-4"><div className="flex gap-2"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-warn"/><div><div className="text-xs font-bold text-[#74522a]">Open truth gaps</div><ul className="mt-2 space-y-1.5 text-[11px] leading-4 text-[#8c6a42]">{profile.gaps.map(gap=><li key={gap}>• {gap}</li>)}</ul></div></div></div>
      </Section>
      <Section title="Projects & affiliations" subtitle="Evidence-backed work history" icon={Building2}>
        {profile.affiliations.map(({name,role,meta,kind})=>{const Icon=kind==="company"?Building2:kind==="work"?Users:UserRound;return <div key={name} className="flex items-center gap-3 border-b border-line py-3 last:border-0"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-surface-2 text-accent"><Icon className="h-4 w-4"/></div><div><div className="text-xs font-bold">{name}</div><div className="text-[11px] text-muted">{role}</div></div><span className="ml-auto text-[10px] text-muted-2">{meta}</span></div>})}
      </Section>
    </div>
   </div>
 </div>;
}

function Section({title,subtitle,icon:Icon,children}:{title:string;subtitle:string;icon:React.ElementType;children:React.ReactNode}){return <section className="panel rounded-lg p-5"><div className="mb-5 flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-accent-soft text-accent"><Icon className="h-4 w-4"/></div><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-0.5 text-[11px] text-muted">{subtitle}</p></div><button className="ml-auto text-muted-2"><ArrowUpRight className="h-4 w-4"/></button></div>{children}</section>}
function Social({icon:Icon}:{icon:React.ElementType}){return <button className="flex h-8 w-8 items-center justify-center rounded-lg border border-line bg-white text-muted hover:text-accent"><Icon className="h-3.5 w-3.5"/></button>}
function Score({icon:Icon,tone,label,value,hint,warning}:{icon:React.ElementType;tone:"blue"|"purple"|"green"|"amber";label:string;value:string;hint:string;warning?:boolean}){const colors={blue:"bg-[#e7eef9] text-[#4f72a5]",purple:"bg-[#eee8f8] text-[#7656a5]",green:"bg-[#e4f2ed] text-[#347c67]",amber:"bg-[#fff0dc] text-[#a96e2d]"};return <div className="rounded-lg border border-line bg-surface-2 p-4"><div className="flex items-start justify-between"><div className="text-[10px] font-bold uppercase tracking-wider text-muted">{label}</div><span className={`flex h-8 w-8 items-center justify-center rounded-md ${colors[tone]}`}><Icon className="h-4 w-4"/></span></div><div className="mt-1 flex items-end gap-1"><span className="text-2xl font-bold">{value}</span><span className="pb-1 text-[10px] text-muted">/100</span></div><div className={`mt-2 text-[10px] font-semibold ${warning?"text-warn":"text-success"}`}>{hint}</div></div>}
function Assessment({title,rating,trend,confidence,body}:{title:string;rating:string;trend:string;confidence:number;body:string}){const ratingTone=rating==="Bullish"?"bg-[#e4f2ed] text-success":rating==="Bearish"?"bg-[#fbe8e9] text-danger":"bg-[#fff1df] text-warn";const titleIcon=title==="Founder"?UserRound:title==="Market"?Globe2:Crosshair;const Icon=titleIcon;return <div className="rounded-lg border border-line bg-surface-2 p-4"><div className="mb-3 flex items-center justify-between"><span className="flex items-center gap-1.5 text-xs font-bold"><Icon className="h-3.5 w-3.5 text-accent-muted"/>{title}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${ratingTone}`}>{rating}</span></div><p className="min-h-12 text-[11px] leading-4 text-muted">{body}</p><div className="mt-3 flex items-center gap-1.5 text-[10px] font-semibold text-[#7656a5]"><TrendingUp className="h-3 w-3"/>{trend}<span className="ml-auto text-muted">{confidence}% confidence</span></div></div>}
function eventTone(type:string){if(["Traction","Milestone","Validation"].includes(type))return{dot:"bg-[#4f9b84]",badge:"bg-[#e5f3ed] text-[#347c67]"};if(["Product","Science","Research","Work sample"].includes(type))return{dot:"bg-[#6d8fbd]",badge:"bg-[#e7eef9] text-[#4f72a5]"};if(["Team","Career","Discovery"].includes(type))return{dot:"bg-[#8b6db6]",badge:"bg-[#eee8f8] text-[#7656a5]"};return{dot:"bg-[#d39a55]",badge:"bg-[#fff1df] text-[#a96e2d]"}}
function Coverage({label,value}:{label:string;value:number}){return <div><div className="mb-1.5 flex justify-between text-[11px]"><span className="font-medium text-ink-2">{label}</span><span className="font-bold text-muted">{value}%</span></div><div className="h-2 rounded-full bg-surface-3"><div className="h-full rounded-full bg-accent-muted" style={{width:`${value}%`}}/></div></div>}

function RelationshipGraph({founderName,initials,relations}:{founderName:string;initials:string;relations:FounderRelation[]}){
 const positions=[{x:82,y:68,r:34},{x:350,y:65,r:31},{x:362,y:222,r:34},{x:88,y:230,r:34}];
 const fills={company:"#dce8f3",person:"#e6edf5",institution:"#eef0e5",investor:"#eee8f4"};
 return <div><svg viewBox="0 0 430 300" className="w-full overflow-visible" role="img" aria-label={`${founderName} relationship graph`}>
 <defs><filter id="shadow"><feDropShadow dx="0" dy="3" stdDeviation="4" floodColor="#6b7f99" floodOpacity=".18"/></filter></defs>
 <g stroke="#b9c6d6" strokeWidth="1.4">{relations.slice(0,4).map((relation,index)=>{const p=positions[index];return <line key={relation.label} x1="215" y1="145" x2={p.x} y2={p.y} strokeDasharray={relation.verified?undefined:"4 5"}/>})}</g>
 <GraphNode x={215} y={145} r={43} fill="#415a7d" label={initials} sub="Founder" inverse/>
 {relations.slice(0,4).map((relation,index)=>{const p=positions[index];return <GraphNode key={relation.label} {...p} fill={fills[relation.kind]} label={relation.label} sub={relation.sub}/>})}
 </svg><div className="mt-1 flex flex-wrap gap-3 text-[9px] text-muted"><span className="flex items-center gap-1"><i className="h-px w-4 bg-[#9eafc4]"/>Verified relationship</span><span className="flex items-center gap-1"><i className="w-4 border-t border-dashed border-[#9eafc4]"/>Inferred connection</span></div></div>}
function GraphNode({x,y,r,fill,label,sub,inverse}:{x:number;y:number;r:number;fill:string;label:string;sub:string;inverse?:boolean}){return <g filter="url(#shadow)"><circle cx={x} cy={y} r={r} fill={fill} stroke="white" strokeWidth="4"/><text x={x} y={y-2} textAnchor="middle" fontSize="11" fontWeight="700" fill={inverse?"white":"#344258"}>{label}</text><text x={x} y={y+12} textAnchor="middle" fontSize="8" fill={inverse?"#dce5ef":"#8291a5"}>{sub}</text></g>}
