import { useNavigate } from "react-router";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, Compass, Inbox, Scale, Target } from "lucide-react";

const priorities=[
 {company:"NeuraGrid",founder:"Alice Chen",source:"Inbound",stage:"Final diligence",action:"Verify €48k ARR",due:"6h 20m",color:"amber"},
 {company:"RelayOps",founder:"Marcus Johnson",source:"Outbound",stage:"Memo ready",action:"Review investment memo",due:"11h 05m",color:"blue"},
 {company:"Kanso Robotics",founder:"Yuki Tanaka",source:"Inbound",stage:"Screening",action:"Review commercial gap",due:"18h 40m",color:"purple"},
];

export function HomePage(){
 const navigate=useNavigate();
 return <div className="mx-auto max-w-[1220px] pb-10">
  <section className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="eyebrow mb-2">Investment workspace</div><h1 className="text-3xl font-bold tracking-tight">Good morning, Sophie</h1><p className="mt-2 text-sm text-muted">Here’s what needs your attention across sourcing and decisions.</p></div><button onClick={()=>navigate('/thesis')} className="flex w-fit items-center gap-3 rounded-md border border-line bg-white px-4 py-2.5 shadow-sm"><span className="h-2 w-2 rounded-full bg-success"/><div className="text-left"><div className="text-xs font-bold">Berlin Deep Tech</div><div className="text-[10px] text-muted">Active thesis · v3</div></div><ArrowRight className="h-3.5 w-3.5 text-muted"/></button></section>
  <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Inbox} label="New inbound" value="7" hint="3 need review" color="purple"/><Metric icon={Compass} label="New discoveries" value="18" hint="6 high match" color="green"/><Metric icon={Clock3} label="SLA at risk" value="2" hint="Due within 12h" color="amber"/><Metric icon={CheckCircle2} label="Decided this week" value="14" hint="71% proceeded" color="blue"/></div>
  <div className="mb-6 grid gap-4 lg:grid-cols-3"><Action icon={Inbox} color="purple" title="Review inbound" text="7 founder applications and deck analyses are waiting." button="Open inbox" onClick={()=>navigate('/inbound')}/><Action icon={Compass} color="green" title="Discover outbound" text="Explore founders surfaced from public activity signals." button="Open discover" onClick={()=>navigate('/sourcing')}/><Action icon={Scale} color="amber" title="Make decisions" text="3 cases completed screening and need human review." button="Open queue" onClick={()=>navigate('/decisions')}/></div>
  <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="panel rounded-lg"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-bold">Priority opportunities</h2><p className="text-[11px] text-muted">Ordered by SLA risk and next action</p></div><button onClick={()=>navigate('/decisions')} className="text-xs font-bold text-accent">View all</button></div>{priorities.map(item=><button key={item.company} onClick={()=>navigate('/decisions')} className="grid w-full items-center gap-3 border-b border-line px-5 py-4 text-left last:border-0 sm:grid-cols-[1.2fr_.8fr_1.2fr_auto]"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-md text-xs font-bold ${tone(item.color)}`}>{item.company.slice(0,2).toUpperCase()}</span><div><div className="text-xs font-bold">{item.company}</div><div className="text-[10px] text-muted">{item.founder} · {item.source}</div></div></div><Cell label="Stage" value={item.stage}/><div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-2">Next action</div><div className="mt-1 flex items-center gap-1 text-[11px] font-semibold"><AlertTriangle className="h-3 w-3 text-warn"/>{item.action}</div></div><span className="flex items-center gap-1 text-[10px] font-bold text-danger"><Clock3 className="h-3 w-3"/>{item.due}</span></button>)}</section><section className="panel rounded-lg p-5"><div className="mb-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-accent-soft text-accent"><Target className="h-4 w-4"/></span><div><h2 className="text-sm font-bold">Active thesis</h2><p className="text-[11px] text-muted">Berlin Deep Tech · v3</p></div></div>{["AI Infrastructure","Pre-seed / Seed","DACH & Europe","€250k – €500k"].map(item=><div key={item} className="mb-2 flex items-center gap-2 rounded-md bg-surface-2 px-3 py-2.5 text-[11px] font-semibold"><CheckCircle2 className="h-3.5 w-3.5 text-success"/>{item}</div>)}<button onClick={()=>navigate('/thesis')} className="mt-4 flex items-center gap-1 text-xs font-bold text-accent">Edit thesis <ArrowRight className="h-3.5 w-3.5"/></button></section></div>
 </div>
}

function tone(color:string){return color==="purple"?"bg-[#eee8f8] text-[#7656a5]":color==="green"?"bg-[#e4f2ed] text-[#347c67]":color==="amber"?"bg-[#fff1df] text-[#a96e2d]":"bg-[#e7eef9] text-[#5074a8]"}
function Metric({icon:Icon,label,value,hint,color}:{icon:React.ElementType;label:string;value:string;hint:string;color:string}){return <div className="panel flex items-center gap-3 rounded-lg p-4"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${tone(color)}`}><Icon className="h-4 w-4"/></span><div><div className="text-lg font-bold">{value}</div><div className="text-[10px] font-semibold text-ink-2">{label}</div></div><span className="ml-auto self-end text-[9px] text-muted">{hint}</span></div>}
function Action({icon:Icon,color,title,text,button,onClick}:{icon:React.ElementType;color:string;title:string;text:string;button:string;onClick:()=>void}){return <button onClick={onClick} className="panel group rounded-lg p-5 text-left transition hover:-translate-y-0.5"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${tone(color)}`}><Icon className="h-5 w-5"/></span><h2 className="mt-4 text-sm font-bold">{title}</h2><p className="mt-1.5 text-[11px] leading-5 text-muted">{text}</p><span className="mt-4 flex items-center gap-1 text-xs font-bold text-accent">{button}<ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1"/></span></button>}
function Cell({label,value}:{label:string;value:string}){return <div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-2">{label}</div><div className="mt-1 text-[11px] font-semibold">{value}</div></div>}
