import { useRef, useState } from "react";
import { ArrowRight, Building2, CheckCircle2, FileText, FileUp, Globe2, Mail, ShieldCheck, Sparkles, UserRound, X } from "lucide-react";

export function InboundPage(){
 const fileInput=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [submitted,setSubmitted]=useState(false);
 if(submitted)return <InboundSuccess company="Aperture AI" onReset={()=>{setSubmitted(false);setFile(null)}}/>;
 return <div className="mx-auto max-w-[980px] pb-10"><div className="mb-7 max-w-2xl"><div className="eyebrow mb-2">Inbound application</div><h1 className="page-title">Tell us what you’re building</h1><p className="page-description">Start with your company and deck. FirstCheck24 extracts team, product, market and traction, then asks only for decision-critical gaps.</p></div>
  <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}} className="panel rounded-lg p-5 md:p-6">
   <div className="mb-6 flex items-center gap-3 border-b border-line pb-4"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-[#eee8f8] text-[#7656a5]"><FileUp className="h-4 w-4"/></span><div><h2 className="section-title">Minimum application</h2><p className="supporting-text">Takes about two minutes</p></div></div>
   <div className="grid gap-4 sm:grid-cols-2"><Field icon={Building2} label="Company or project name" placeholder="Aperture AI" required/><Field icon={UserRound} label="Founder name" placeholder="Your full name" required/><Field icon={Mail} label="Founder email" placeholder="you@company.com" type="email" required/><Field icon={Globe2} label="Website or demo" placeholder="https://"/></div>
   <div className="mt-5"><label className="mb-2 block text-[13px] font-bold text-ink-2">Pitch deck <span className="text-danger">*</span></label><input ref={fileInput} type="file" accept=".pdf,.ppt,.pptx" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file?<div className="flex items-center gap-3 rounded-md border border-success/30 bg-[#f0f8f5] p-4"><span className="flex h-10 w-10 items-center justify-center rounded-md bg-[#e1f1eb] text-success"><FileText className="h-5 w-5"/></span><div className="min-w-0"><div className="truncate text-[13px] font-bold">{file.name}</div><div className="numeric mt-0.5 text-[11px] text-muted">{Math.max(1,Math.round(file.size/1024))} KB · Ready to parse</div></div><button type="button" onClick={()=>setFile(null)} className="ml-auto text-muted"><X className="h-4 w-4"/></button></div>:<button type="button" onClick={()=>fileInput.current?.click()} className="flex w-full flex-col items-center border border-dashed border-line-2 bg-surface-2 px-5 py-9 text-center transition hover:border-accent-muted hover:bg-accent-soft"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white text-accent shadow-sm"><FileUp className="h-5 w-5"/></span><span className="mt-3 text-[13px] font-bold">Choose your pitch deck</span><span className="mt-1 text-[11px] text-muted">PDF or PowerPoint · up to 25 MB</span></button>}</div>
   <label className="mt-5 flex items-start gap-2.5 text-xs leading-5 text-muted"><input type="checkbox" required className="mt-1 accent-[#415a7d]"/><span>I confirm that I’m authorized to share these materials for investment review.</span></label>
   <button type="submit" className="mt-5 flex items-center gap-2 rounded-md bg-accent px-5 py-3 text-sm font-semibold text-white">Submit for analysis <ArrowRight className="h-4 w-4"/></button>
  </form><aside className="space-y-3"><Info icon={Sparkles} color="blue" title="AI extracts the details" text="Team, product, market, traction and claims are read from your deck."/><Info icon={ShieldCheck} color="green" title="Evidence stays traceable" text="Every extracted claim links back to its exact source and page."/><Info icon={CheckCircle2} color="amber" title="Only relevant follow-ups" text="We ask only for missing information needed for a reliable decision."/></aside></div>
 </div>
}

function Field({icon:Icon,label,placeholder,type="text",required=false}:{icon:React.ElementType;label:string;placeholder:string;type?:string;required?:boolean}){return <label className="block"><span className="mb-2 block text-[13px] font-bold text-ink-2">{label}{required&&<span className="text-danger"> *</span>}</span><span className="relative block"><Icon className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-2"/><input type={type} required={required} placeholder={placeholder} className="w-full rounded-md border border-line bg-surface-2 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-accent-muted focus:bg-white"/></span></label>}
function Info({icon:Icon,color,title,text}:{icon:React.ElementType;color:"blue"|"green"|"amber";title:string;text:string}){const tones={blue:"bg-[#e7eef9] text-[#5074a8]",green:"bg-[#e4f2ed] text-[#347c67]",amber:"bg-[#fff1df] text-[#a96e2d]"};return <div className="panel rounded-lg p-4"><span className={`flex h-8 w-8 items-center justify-center rounded-md ${tones[color]}`}><Icon className="h-4 w-4"/></span><div className="mt-3 text-[13px] font-bold">{title}</div><p className="mt-1 text-xs leading-5 text-muted">{text}</p></div>}
function InboundSuccess({company,onReset}:{company:string;onReset:()=>void}){return <div className="mx-auto max-w-[680px] py-12"><div className="panel rounded-lg p-8 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-lg bg-[#e4f2ed] text-success"><CheckCircle2 className="h-7 w-7"/></span><h1 className="mt-5 text-2xl font-bold">Application received</h1><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted">We’re parsing {company}’s deck and building an evidence-backed opportunity profile.</p><div className="mx-auto mt-7 grid max-w-md gap-2 text-left">{["Extract team, product and traction","Compare against the active fund thesis","Identify only decision-critical gaps"].map((item,index)=><div key={item} className="flex items-center gap-3 rounded-md bg-surface-2 p-3 text-xs font-medium"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-accent text-[10px] text-white">{index+1}</span>{item}</div>)}</div><button onClick={onReset} className="mt-7 text-xs font-bold text-accent">Submit another application</button></div></div>}
