import { useNavigate } from "react-router";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, Filter, Inbox, Search, ShieldCheck, Sparkles } from "lucide-react";

const applications=[
 {company:"NeuraGrid",founder:"Alice Chen",stage:"Pre-seed",sector:"AI Infrastructure",received:"18 min ago",match:91,status:"Extraction complete",ask:"€100k",risk:"ARR verification",color:"blue"},
 {company:"Kanso Robotics",founder:"Yuki Tanaka",stage:"Pre-seed",sector:"Robotics",received:"2h ago",match:79,status:"Needs review",ask:"€250k",risk:"Commercial ownership",color:"purple"},
 {company:"HelixForge",founder:"David Park",stage:"Seed",sector:"Biotech",received:"5h ago",match:82,status:"Extraction complete",ask:"€500k",risk:"Pipeline evidence",color:"green"},
 {company:"Lattice Health",founder:"Sarah Williams",stage:"Pre-seed",sector:"Clinical AI",received:"Yesterday",match:76,status:"Missing information",ask:"€150k",risk:"Regulatory pathway",color:"amber"},
];

export function InboundInboxPage(){
 const navigate=useNavigate();
 return <div className="mx-auto max-w-[1160px] pb-10">
  <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow mb-2">Founder applications</div><h1 className="text-3xl font-bold tracking-tight">Inbound inbox</h1><p className="mt-2 text-sm text-muted">Review submitted decks, extracted claims and thesis fit.</p></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-md border border-line bg-white px-3 py-2 text-xs font-semibold"><Filter className="h-3.5 w-3.5"/>Filter</button><button className="rounded-md bg-accent px-4 py-2 text-xs font-semibold text-white">Copy application link</button></div></div>
  <div className="mb-5 grid gap-3 sm:grid-cols-3"><Stat icon={Inbox} value="7" label="New applications" tone="purple"/><Stat icon={Sparkles} value="5" label="Decks parsed" tone="blue"/><Stat icon={Clock3} value="2" label="Need attention" tone="amber"/></div>
  <section className="panel rounded-lg"><div className="flex items-center gap-3 border-b border-line px-5 py-4"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-2"/><input placeholder="Search applications..." className="w-full rounded-md border border-line bg-surface-2 py-2 pl-9 pr-3 text-xs outline-none focus:border-accent-muted"/></div><span className="text-[10px] text-muted">Sorted by thesis match</span></div><div>{applications.map(app=><button key={app.company} onClick={()=>navigate('/founders/a1b2c3d4-e5f6-7890-abcd-ef1234567890')} className="grid w-full items-center gap-4 border-b border-line px-5 py-4 text-left last:border-0 lg:grid-cols-[1.35fr_.8fr_.7fr_1.1fr_auto]"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-md text-xs font-bold ${tone(app.color)}`}>{app.company.slice(0,2).toUpperCase()}</span><div><div className="text-xs font-bold">{app.company}</div><div className="text-[10px] text-muted">{app.founder} · {app.sector}</div></div></div><Cell label="Stage / ask" value={`${app.stage} · ${app.ask}`}/><div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-2">Thesis match</div><div className="mt-1 flex items-center gap-1 text-xs font-bold text-success"><ShieldCheck className="h-3 w-3"/>{app.match}%</div></div><div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-2">AI review</div><div className="mt-1 flex items-center gap-1 text-[11px] font-semibold"><StatusIcon status={app.status}/>{app.status}</div><div className="mt-1 text-[9px] text-muted">Open: {app.risk}</div></div><div className="flex items-center gap-3"><span className="text-[9px] text-muted">{app.received}</span><ArrowRight className="h-4 w-4 text-accent"/></div></button>)}</div></section>
  <div className="mt-4 flex items-center gap-2 text-[10px] text-muted"><FileText className="h-3.5 w-3.5 text-accent"/>The founder-facing form is a shareable public link and does not appear in the VC navigation.</div>
 </div>
}
function tone(color:string){return color==="purple"?"bg-[#eee8f8] text-[#7656a5]":color==="green"?"bg-[#e4f2ed] text-[#347c67]":color==="amber"?"bg-[#fff1df] text-[#a96e2d]":"bg-[#e7eef9] text-[#5074a8]"}
function Stat({icon:Icon,value,label,tone:kind}:{icon:React.ElementType;value:string;label:string;tone:"purple"|"blue"|"amber"}){const colors={purple:"bg-[#eee8f8] text-[#7656a5]",blue:"bg-[#e7eef9] text-[#5074a8]",amber:"bg-[#fff1df] text-[#a96e2d]"};return <div className="panel flex items-center gap-3 rounded-lg p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-md ${colors[kind]}`}><Icon className="h-4 w-4"/></span><div><div className="text-lg font-bold">{value}</div><div className="text-[10px] text-muted">{label}</div></div></div>}
function Cell({label,value}:{label:string;value:string}){return <div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-2">{label}</div><div className="mt-1 text-[11px] font-semibold">{value}</div></div>}
function StatusIcon({status}:{status:string}){return status==="Extraction complete"?<CheckCircle2 className="h-3 w-3 text-success"/>:status==="Missing information"?<AlertTriangle className="h-3 w-3 text-danger"/>:<Sparkles className="h-3 w-3 text-warn"/>}
