"""add discovery config to thesis

Revision ID: e093be299381
Revises: 007
Create Date: 2026-07-19 13:56:57.100701
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e093be299381'
down_revision: str | None = '007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_theses",
        sa.Column(
            "discovery_queries",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "investment_theses",
        sa.Column(
            "source_freshness_days",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_theses', 'source_freshness_days')
    op.drop_column('investment_theses', 'discovery_queries')
    # ### end Alembic commands ###
